version: '3.8'

services:
  web:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      
  api:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
    command: ['sh', 'docker-entrypoint.sh']
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
